openapi: 3.0.3
info:
  version: 1.0.0
  title: SHARK visit ID log
  description: Get/Post ID from/to log (PostGIS/SQLite database)
tags:
- name: sharkids
paths:
  /getid:
    get:
      operationId: app.get_id
      tags:
      - sharkids
      description: Return a json with year_id as string
      parameters:
        - $ref: '#/components/parameters/timestamp'
        - $ref: '#/components/parameters/shipc'
        - $ref: '#/components/parameters/east'
        - $ref: '#/components/parameters/north'
#        - $ref: '#/components/parameters/lon_dd'
#        - $ref: '#/components/parameters/lat_dd'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SharkId'
        404:
          description: Not found
components:
  schemas:
    SharkId:
      type: object
  parameters:
    timestamp:
      in: query
      name: timestamp
      schema:
        type: string
    shipc:
      in: query
      name: shipc
      schema:
        type: string
    east:
      in: query
      name: east
      schema:
        type: number
    north:
      in: query
      name: north
      schema:
        type: number
#    lon_dd:
#      in: query
#      name: lon_dd
#      schema:
#        type: number
#    lat_dd:
#      in: query
#      name: lat_dd
#      schema:
#        type: number